### ISSUE TITLE
apiVersion capability condition check always fails when generating helmchart with cdk8s

### ISSUE THREAD

**Issue by bacht-fidi** [puzzle/cert-manager-webhook-dnsimple#49]
Hello there,

When generating the helm charts with cdk8s we see that the go template condition always fails since the charts are executed  outside of a k8s cluster. Hence deployment always fails. Example:

[APIService YAML](https://github.com/puzzle/cert-manager-webhook-dnsimple/blob/master/charts/cert-manager-webhook-dnsimple/templates/apiservice.yaml)
```yaml
{{- $APIRegistrationAPIVersion := ternary "apiregistration.k8s.io/v1" "apiregistration.k8s.io/v1beta1" (.Capabilities.APIVersions.Has "apiregistration.k8s.io/v1") -}}
apiVersion: {{ $APIRegistrationAPIVersion }}
kind: APIService
metadata:
  name: v1alpha1.{{ include "dnsimple-webhook.api-group" . }}
  labels:
    app: {{ include "dnsimple-webhook.name" . }}
    chart: {{ include "dnsimple-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ include "dnsimple-webhook.servingCertificate" . }}"
spec:
  group: {{ include "dnsimple-webhook.api-group" . }}
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: {{ include "dnsimple-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
  version: v1alpha1
```

This condition would set the apiVersion of the APIService to "apiregistration.k8s.io/v1beta1". The same behaviour is observable with the pki.yaml chart.

![grafik](https://github.com/user-attachments/assets/721c2996-3c4c-4279-8459-328aaf809aba)

Is it possible to set this value in the value.yaml charts instead of a condition or as a static value in the template?
